image: atlassian/default-image:latest

options:
  runtime:
    cloud:
      atlassian-ip-ranges: true

pipelines:
  branches:
    development:
      - step:
          name: Dev Deployment
          size: 2x
          deployment: Development
          script:
            - mkdir -p ~/.ssh
            - echo "$PRIVATE_KEY" > ~/.ssh/key.pem
            - chmod 600 ~/.ssh/key.pem
            - cat ~/.ssh/key.pem
            - ssh -v -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "echo 'Connected to Dev'"
            - ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "cd ~/getirnow-frontend && git checkout production"
            - ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "cd ~/getirnow-frontend && git pull"
            - ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "cd ~/getirnow-frontend && make rebuild"
            - ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "docker system prune -a --volumes -f"
            - echo "✅ Dev Deployment finished!"

    production:
      - step:
          name: Production Deployment
          size: 2x
          deployment: Production
          script:
            - echo -e "-----BEGIN OPENSSH PRIVATE KEY-----\n\
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEA3HZosroZL8tKWkeGJQVKKjkfNfcefCQEJdcJHEjUrG31TGtNI3ZqTaDGFlL2JaoOMt4DN7hcrI1sT2Df5/gUXk7RRlqXoAxV657qX07J+bRMUEV+pRFT3BHyhE0sHrejncggVt8W0v5GxDfSrYa6Zp+IzlNwx9LchH8AYMbMDV2oF/qybTsnujhVZQAZvIm9q66PY0W5I2pIRwgbiTsi4AIlH3yZlXnH8lAHDgbNV5m+b6RP62htWtHbgbSbycPDuqez+wiPk/37NjkyhCWMIeGJ9suKIt2TxEpvTyp04XbDptbt6G+ub+Wsbq2i0fZwoMQ9WjdXyAhDO3hK1T6PD2xjEVo8f4WctzuFrCQgAB/hzgoXnsgHf8XKhINFWnUUnGwxomjZbqMKOJLWH3C6WGb+MQayg6VkS5RfcBO/CRmIYHe49rleJvLB9gMMeluQwC23D1N3j9jeqoQnrapjtmwDHRFjManpyNDFayZsRA546kJizDQArtj7wmXe3GgNEG3akUA7pPNKJmu9+9gwhKctXMyqtqSXPOXp/hiHdns29bpFLR2n5slra/u4LaROs2JdZt4Q2/60Hk1rm3Zx0KUvlv+5RRMOD5hs2dcG3VLfoiYoU460/vpZg5yg3CZ1sRH4A+GtiC4VGrPkTmg6splWbSfJ+ElgNwxohI6jyh8AAAdI/xWdDP8VnQwAAAAHc3NoLXJzYQAAAgEA3HZosroZL8tKWkeGJQVKKjkfNfcefCQEJdcJHEjUrG31TGtNI3ZqTaDGFlL2JaoOMt4DN7hcrI1sT2Df5/gUXk7RRlqXoAxV657qX07J+bRMUEV+pRFT3BHyhE0sHrejncggVt8W0v5GxDfSrYa6Zp+IzlNwx9LchH8AYMbMDV2oF/qybTsnujhVZQAZvIm9q66PY0W5I2pIRwgbiTsi4AIlH3yZlXnH8lAHDgbNV5m+b6RP62htWtHbgbSbycPDuqez+wiPk/37NjkyhCWMIeGJ9suKIt2TxEpvTyp04XbDptbt6G+ub+Wsbq2i0fZwoMQ9WjdXyAhDO3hK1T6PD2xjEVo8f4WctzuFrCQgAB/hzgoXnsgHf8XKhINFWnUUnGwxomjZbqMKOJLWH3C6WGb+MQayg6VkS5RfcBO/CRmIYHe49rleJvLB9gMMeluQwC23D1N3j9jeqoQnrapjtmwDHRFjManpyNDFayZsRA546kJizDQArtj7wmXe3GgNEG3akUA7pPNKJmu9+9gwhKctXMyqtqSXPOXp/hiHdns29bpFLR2n5slra/u4LaROs2JdZt4Q2/60Hk1rm3Zx0KUvlv+5RRMOD5hs2dcG3VLfoiYoU460/vpZg5yg3CZ1sRH4A+GtiC4VGrPkTmg6splWbSfJ+ElgNwxohI6jyh8AAAADAQABAAACABv25Rbupi060yaadfiSMDMk5cGZpANJKkGGgkBVOKzakcfswG8kIR3Rq+6+/TwP0xc+tBfISfEVS0zSU/R/sk24H7GV4i/KAMgPc1k9jD8hUKDJ/+N+TC3ZFPMVOuh2kMl9ziRWzfVbjaxsDEw4j8JesCLD0MV4CMLBvVGJRe7YF29bPHDAlSx44tQZ7CnPKwDw9n04JeDJJXvlGmEQ4D6b5wuUaYLdXLBu2EY+NKPM+6v7oquQpnZjsj1EpJI2Q8iUZy8LifLSv5/EJ5U9kgXmLvLgJJiBlLHMY0webY7/2pd6Idle+Th2YKX1XnbVlLm/yqx74qWb7rNHce6Urd6hsUFbDwjJ4pQB5vxTyeUHBX0PSLZMl4BL3i+Nrj6khyGeqdx+i8jSADexiC8BknD1vPgPRFk9UOzA8xL/5I6LbTyJNqdQxtXk1lr8ccrAwHLO1Ie/apwa3hGJpiidxi5II1M8LzpWkkBC0eYeka+Fl00u8IxzcWBYV1NDHrFnE9zzyxtlhRwbaK0/4z516T7N3H5dyd/G5tTAkLtwevusokLC4dgC/JxWQzV5n3Uu4T1YA28nRdB4UwXnD2zowMLA2TOBtiAA2CxHYdWcD2A431CusNkneIjZEIniAd20ZKiXD1ZzTq6xTwX4GoFjfurag6MhiKEICP9IulJUIx7ZAAABAQCs98vpasOy9WAyCJBT539i/P0jlNB9yMomoD2L6LIgf4lNN3ubmT9nXS/KVq7ccm/uqoXt++uwadPDYg/IPsRYYpvJuwCP7RFOHJuFhuXNCOKhlUq/Ee8nsaEd/YXLXB3xHTvEU2LCr9AHL1y/IJSRUQD+1D6/TEiF9jQyYNU++0yrPwUxCqxkpcknQPs0VmZ9k067y6AYeReaNOMlYJyR2ORaJPuiHCUftmFunJbJ0gAmge8D6m4yn14XA63QNilpYkzCgmc2zT93W4fSqVZ5Kq+lK3rjPA9AFf4MxugXS5hmkDtVSyFTIGA4xOROYGl6pghCYqpROOSJ0+w+BzTZAAABAQDxPjbUT/v9pTRZYBsD7TX3Cv/SlFXg8nIupnXMEj+9Whn9WZ8u0saB231g2ridX0MzawRUYEpwICDzhznMNzHoXFgdFcR+swX2nnotM9ltGut1DSnHl8CzpykZWTBez66SiFuUp+c6QbnBbD5tHPj9Iovv7McRuAciIpannYAxZARaxtazSp5KHFHQz1sbI0LMVAaT1aLteHdR+cD4qTiG1SB3w9QD3uaK/Y2JMEDHYsmGqXDbAz17udx3lTv30OYsojv0SxKO2AvNGXJcdWqSlLiPbwGhmr06qebvF57DhsJ7LgrHOWEJeJ0d3X55h4HB3bFDhArXrcmB1ivAkdodAAABAQDp8sd7aSV8OPwrr42HmgVJ7Y+GYt7N1hx7309MEc4Ld63z7PLM4SMSB7kjwirvxBPu70oBmylb4NmcMybSPt+Zgz7g3h8vPSOFK1eIthIGeWqvYke5Egz/hKpqC8tc7BJ+rT+T4BMqQcM1l0pVmeBSwG8RNuDD3wjKCzmmHQF/g3IEWuvVklequbZomQG1JYB1RwWnObqZ4HvfdshXv5C2hEfYFuR8GEnZIIzoM4WQ0FBt1S8NtZV0Hn797C1LBq2hugdI2OlJWyZkEPLUfYu/yIofp09EmeSTNLXSGQAYnQxYhf4SgSYA/XS2j/1LKxinekjd2Cf++/T0vBKT8iBrAAAAEGJpdGJ1Y2tldC1kZXBsb3kBAg==\n\
              -----END OPENSSH PRIVATE KEY-----" > key.pem
            - chmod 600 key.pem
            - cat key.pem  # Debug: Verify key file contents
            - ssh -v -i key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "echo 'Connected to Prod'"
            - ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@ec2-52-91-162-18.compute-1.amazonaws.com "
                cd ~/getirnow-frontend &&
                git checkout production &&
                git pull &&
                make rebuild &&
                docker system prune -a --volumes -f
              "
            - echo "✅ Production Deployment finished!"