image: atlassian/default-image:latest

options:
  runtime:
    cloud:
      atlassian-ip-ranges: true

pipelines:
  branches:
    development:
      - step:
          name: Dev Development
          size: 2x
          deployment: Development
          script:
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP echo "Starting Deployment"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/myproject && git checkout development"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/myproject && git pull"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/myproject && sudo make rebuild"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker system prune -a --volumes -f"
            - echo "Deployment finished successfully!"

    production:
      - step:
          name: Production
          size: 2x
          deployment: Production
          script:
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP echo "Starting Deployment"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/getirnow-frontend && git checkout production"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/getirnow-frontend && git pull"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/getirnow-frontend && make rebuild"
            - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker system prune -a --volumes -f"
            - echo "Deployment finished successfully!"
