name: Deploy to EC2

on:
  push:
    branches:
      - development
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        #   ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run deployment on EC2
        run: |
          echo "Starting Deployment1"

          if [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ~/myproject && git checkout development && git pull origin development && docker system prune -a --volumes -f && make rebuild"
          
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ~/getirnow-frontend && git checkout production && git pull && make rebuild && docker system prune -a --volumes -f"
          
          fi

      - name: Done
        run: echo "Deployment finished successfully!"
